#! /bin/bash
#
# This script will generate a single entity in Symfony2
#
# @version	1.3
# @author	Jesse Dobbelaere <jesse@dobbelaere-ae.be>

# Read table name
read -p "Enter your database table name: " name
echo Creating Symfony2 entity...

cd ../www

# Set first character to uppercase
tableName="$(tr '[:lower:]' '[:upper:]' <<< ${name:0:1})${name:1}"

# Generate metadata
php app/console doctrine:mapping:convert xml ./src/MatchTracker/Bundle/AppBundle/Resources/config/doctrine/metadata/orm --from-database --filter="$tableName" --force

# Generate entity annotations
php app/console doctrine:mapping:import MatchTrackerAppBundle annotation --filter="$tableName"

# Generate entity
php app/console doctrine:generate:entities MatchTrackerAppBundle:$tableName --no-backup

echo ... Done!

